### ISSUE TITLE
Feature Request: Support for Turbo V2

### ISSUE THREAD

**Issue by julianrinaldi** [carleeno/elevenlabs_tts#108]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

I'd like support for ElevenLabs Turbo V2 added. It should be easy and only require about 5 minutes to implement.

### Describe alternatives you've considered

None.

### Additional context

If possible it would be nice if you made it so that writing in any model ID worked. I know there are different options for some, but there must be a way to handle errors related to this. I think it would also be appropriate to make it so that the model IDs are exactly the same as you would call them in the API. To call multilingual V2 in the api docs, the correct format is elevenlabs_multilingual_v2, while in this add-on it is eleven_multilingual_v2. I don't see any reason to shorten it like this as it can only lead to confusion.

**Comment by carleeno** [comment]
> If possible it would be nice if you made it so that writing in any model ID worked

~~Good idea, I'll see if I can do this to help future-proof it, since I don't currently use this and don't notice when new features are added.~~ Turns out you already can, shows that it's been a while since I used this integration myself *facepalm*

> I don't see any reason to shorten it like this as it can only lead to confusion.

~~I think that was just a typo, it doesn't make sense to me either haha.~~ That's what's specified by elevenlabs GET models response.

~~As I'm traveling full-time and don't use HA currently, it's a bit difficult to dev and test on this. I'll see what I can do but I may need your help testing the changes via a pre-release.~~ Looks like it should already do what you're requesting.

**Comment by carleeno** [comment]
@julianrinaldi after reviewing the elevenlabs api docs, I can confirm that it's `eleven_` not `elevenlabs_`

For turbo you can already specify `eleven_turbo_v2` and it should work (for english only). The integration already allows you to enter any model name. However make sure you are using a voice that was created with/for the model you are using, otherwise you will not get good results.

See https://elevenlabs.io/docs/api-reference/get-models to get the correct model names to use in your config/options for this integration.
